deepseek-ai/3FS

docs/design_notes.md
specs/README.md
src/lib/api/UsrbIo.md

Found typos when going through the documentation.

fix(typo): tiny correction in docs

---

docs/design_notes.md

Modify "get:" to "*get*" for consistent formatting and improved readability

fix:[Doc]:fix format of Design Notes

---

benchmarks/storage_bench/StorageBench.h
src/client/cli/admin/DumpChainTable.cc
src/client/cli/admin/DumpChains.cc
src/client/cli/admin/DumpChunkMeta.cc
src/client/cli/admin/DumpInodes.cc
src/client/cli/admin/RenderConfig.cc
src/common/utils/VersionInfo.h
src/fuse/FuseOps.cc
src/storage/store/StorageTarget.cc
src/storage/worker/CheckWorker.cc
src/storage/worker/DumpWorker.cc
tests/meta/event/TestEventLogger.cc

These are necessary for compiling with Ubuntu 24.04 default toolchain/boost.
Greate job! I've tried to run this on Ubuntu 24.04, facing a lot of issues. I eventually failed because I cannot install the RDMA driver. But I don't want to waste my work. So here is part of my modifications to make it compile.
See also
- #43
- #44
- #45
- #46
With these change, plus some changes to third_party, I'm able to build this on Ubuntu 24.04, with `-Werror` removed and https://github.com/google/leveldb/pull/1255, https://github.com/ClickHouse/clickhouse-cpp/pull/296, https://github.com/facebook/rocksdb/pull/11118

add missing headers for new toolchain

---

src/client/meta/ServerSelectionStrategy.h
src/client/storage/StorageClient.h
src/common/app/AppInfo.h
src/common/app/ClientId.h
src/common/utils/OptionalUtils.h
src/common/utils/Result.h
src/common/utils/Status.h
src/common/utils/StrongType.h
src/fbs/core/user/User.h
src/fbs/meta/Schema.h
src/fbs/mgmtd/ChainRef.h
src/fbs/storage/Common.h
src/meta/components/SessionManager.h

When compiled with new toolchain that implements std::format_to, it become ambiguous on which one should be called. Due to argument-dependent lookup, even if we are not `using namespace std;` the std version is still considered. So let's add fmt:: to avoid ambiguous compilation error.

add fmt:: namespace to distinguish from std::format_to

---

src/common/utils/RobinHood.h

Clang has this weird behavior of setting `__GNUC__` to 4, hence clang will always take the if branch. This is suboptimal because std::is_trivially_copyable has almost always been in clang.
starting with clang 15 a warning is raised for the current implementation: warning: builtin __has_trivial_copy is deprecated; use __is_trivially_copyable instead [-Wdeprecated-builtins]
Since we are using -Werror, we should fix this.
Note this resolves the same issue with https://github.com/martinus/robin-hood-hashing/pull/166 , but with a different patch. 
But that PR is never released, and the original repo is archived. So, I just removed this helper. GCC4 is too old to support.

robin hood: resolve warning on new clang

---

benchmarks/storage_bench/StorageBench.cc
src/client/storage/UpdateChannelAllocator.cc
src/fuse/UserConfig.cc
tests/analytics/TestStructuredTraceLog.cc
tests/lib/UnitTestFabric.cc

Newer clang does not allow down cast with brace initialization. Replace them with C-style cast.

explicit down cast

---

.github/workflows/build.yml
README.md
src/lib/api/CMakeLists.txt

This package is not included in Ubuntu 24.04. And we are not actually using it. So just don't link it.

Remove unused dependency libprocps

---

src/common/net/ib/IBSocket.cc
src/common/net/ib/IBSocket.h
src/storage/store/StorageTargets.cc

I notice  IBSocket and StorageTargets would copying the pointer during constructor or erasing, which might introduce unneccssary costs.
Feel free to close this since it's just low-quality contribution :-)

Minor optimize copying of shared_ptr in IBSocket and StorageTargets

---

Cargo.toml
README.md
src/client/trash_cleaner/Cargo.toml
src/client/trash_cleaner/src/main.rs
src/storage/chunk_engine/Cargo.toml

This PR
+ finds that the MSRV is 1.75.0
+ documents MSRV and recommanded Rust version in README
+ runs `cargo fmt`

Document minimum supported rust version

---

CMakeLists.txt
README.md

- Enable compilation on arm64 (aarch64) architecture by conditionally adjusting compiler flags.
- Ensure proper linkage with compiler-rt and libgcc on ARM to resolve missing symbol issues.
- Update README.md with installation instructions for openEuler 2403sp1.

feat(build): add arm64 support for openEuler OS

---

benchmarks/storage_bench/StorageBench.h
src/common/utils/FileUtils.cc
src/fuse/FuseOps.cc
tests/meta/TestCommon.cc
tests/meta/store/ops/TestResolve.cc

We met the following error while building 3FS.
```
/home/symious/testground/3fs/3fs/src/common/utils/FileUtils.cc:9:24: error: 'load_string_file' is deprecated: Use file IO streams instead [-Werror,-Wdeprecated-declarations]
boost::filesystem::load_string_file(path, output);
^
/usr/include/boost/filesystem/string_file.hpp:49:1: note: 'load_string_file' has been explicitly marked deprecated here
BOOST_FILESYSTEM_DETAIL_DEPRECATED("Use file IO streams instead")
^
/usr/include/boost/filesystem/config.hpp:73:49: note: expanded from macro 'BOOST_FILESYSTEM_DETAIL_DEPRECATED'
#define BOOST_FILESYSTEM_DETAIL_DEPRECATED(msg) BOOST_DEPRECATED(msg)
^
/usr/include/boost/config/compiler/clang.hpp:342:46: note: expanded from macro 'BOOST_DEPRECATED'
#define BOOST_DEPRECATED(msg) …
```

Deprecate usage of some functions in boost

---

benchmarks/fio_usrbio/hf3fs_usrbio.cpp

We got the following note while doing fio benchmark.
```
note: both iodepth >= 1 and synchronous I/O engine are selected, queue depth will be capped at 1.
```
This PR is to enable the async IO for fio.

Remove FIO_SYNCIO flag

---

src/common/net/Listener.cc

xgbe is not supported the same as bonding weeks ago(https://github.com/deepseek-ai/3FS/issues/74).
just to fix it.

support listening on xgbe

---

README.md

For a fresh new development environment, the `build-essential` package is required. Otherwise CMAKE error: `No CMAKE_C_COMPILER could be found` will occur. This is confirmed on Ubuntu distros.

add build-essential to dependencies

---

README.md

Hi @SF-Zhou SF  您好， DeepSeek 3FS非常棒 。
为了给OpenCloudOS 开源社区的用户和TencentOS的用户 提供更加易用和快捷的方式
快速构建3FS，我们的OS镜像团队发布了docker镜像，请帮忙看看是否可以合并，谢谢。

Add OpenCloudOS 9 and TencentOS 4 docker image to build 3FS

---

src/client/cli/admin/SetPreferredTargetOrder.cc

The actual type of targetId is uint64_t. In set-preferred-target-order cmd it is parsed as uint32_t. An error will be reported when using set-preferred-target-order cmd.

fix targetId parse in set-preferred-target-order

---

src/storage/sync/ResyncWorker.cc

The targetId should be successor's targetId, because the OfflineTargetReq is sent to successor.

fix OfflineTargetReq.targetId in ResyncWorker, fix #229

---

src/storage/chunk_engine/src/core/engine.rs

When the write batch size exceeds the batch size, the current chunk ID has not been committed to the meta store. The meta cache should not delete the current chunk ID in this scenario. This PR fixes the issue.
See also #238 and #252.

Fix index out of bounds issue in batch_remove

---

src/storage/chunk_engine/src/core/engine.rs

Comparing chunk pointers directly can eliminate the possibility of inconsistency.

Fix potential inconsistency in move chunk

---

src/storage/chunk_engine/src/core/engine.rs
src/storage/chunk_engine/src/meta/meta_store.rs

When performing deletion in commit_chunk, the original chunk may have been relocated by the background `compact_groups`. In this case, the latest chunk location should be obtained after locking to proceed with the commit. This PR fixes this issue.

fix potential inconsistency in commit chunk(s)
